In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [4]:
x = np.random.randint(1,100,(6,6))
print(x)

[[73 42 68 38 24 99]
 [94 15  6 48 68 17]
 [84  1 25 43 93 76]
 [65 76 22 33 38 32]
 [ 9 69  3 30 45 92]
 [19 73 84 23 48 14]]


In [5]:
print(x[0,0])

73


In [6]:
print(x[2,3])

43


In [7]:
print(x[:,4])

[24 68 93 38 45 48]


In [9]:
print(x[:,-2])

[24 68 93 38 45 48]


In [11]:
a = np.array([[1,2],[3,4]])
np.tile(a, (2,2))


array([[1, 2, 1, 2],
       [3, 4, 3, 4],
       [1, 2, 1, 2],
       [3, 4, 3, 4]])

In [12]:
y = ([1,2,3,4],[6,4,2,2],[2,3,4,3],[1,2,4,1])
x = np.array(y)
print(x)

[[1 2 3 4]
 [6 4 2 2]
 [2 3 4 3]
 [1 2 4 1]]


In [13]:
print(x[1:,0:3])

[[6 4 2]
 [2 3 4]
 [1 2 4]]


In [14]:
print(x[:,0])

[1 6 2 1]


In [15]:
print(x[1:3,1:])

[[4 2 2]
 [3 4 3]]


In [16]:
print(x[0,:])

[1 2 3 4]
